### ISSUE TITLE
Autoconf image based on Ubuntu 24.04 failed to run WASI CI build

### ISSUE THREAD

**Issue by corona10** [python/cpython-devcontainers#29]
Image: https://github.com/python/cpython-devcontainers/pkgs/container/autoconf/291871937?tag=2024.10.19.11417401087
We notice this issue through https://github.com/python/cpython/pull/122566#pullrequestreview-2379858448
See related Github Action: https://github.com/python/cpython/actions/runs/11421843985/job/31779110126

```
checking whether float word ordering is bigendian... unknown
configure: error: 

Unknown float word ordering. You need to manually preset
ax_cv_c_float_words_bigendian=no (or yes) according to your system.

    
Traceback (most recent call last):
  File "/home/runner/work/cpython/cpython/Tools/wasm/wasi.py", line 364, in <module>
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
    main()
```

cc @brettcannon

**Comment by corona10** [comment]
cc @erlend-aasland

**Comment by erlend-aasland** [comment]
The failure is because that PR (https://github.com/python/cpython/pull/122566) changes the CI to use the latest devcontainer. We did actually not switch to that yet (see https://github.com/python/cpython/pull/125571), so you get at least two failures:

- check generated files will fail since there is a mismatch between the autoconf devcontainers used by `Tools/build/regen-configure.sh` and the autoconf devcontainer
- the WASI check fails because the autoconf-archive patch does not (yet) work out of the box for us: https://github.com/python/cpython/issues/125698

I'm closing this, since this is already tracked in the following issues:

- https://github.com/python/cpython/issues/125698
- https://github.com/python/cpython-devcontainers/issues/22
